import json, statistics, html
from pathlib import Path
root=Path(__file__).parent
node=json.loads((root/'viewer-boundary-table-parity.json').read_text())
browser={name:json.loads((root/f'viewer-boundary-table-{name}.json').read_text()) for name in ['before','after-first','after']}
medians=[]
for faces in [125000,500000]:
 rows=[r for r in node['timings'] if r['faces']==faces]
 medians.append(dict(faces=faces,beforeMs=statistics.median(r['beforeMs'] for r in rows),afterMs=statistics.median(r['afterMs'] for r in rows)))
changes=['Use Uint32 hash slots, Float64 exact packed keys and saturated Uint8 corner-use counts in the cold boundary path. Resolve hash collisions by full key equality and linear probing.', 'Keep record insertion order separate from hash slots to preserve ordered boundary/wire output. Repeated, self and nonmanifold corner uses retain the existing rules.', 'Keep the original Map path for oversized face lists, more than four million corners or IDs beyond safe numeric packing.', 'Separate scratch-array call scope from returned membership closures. The two-state cache remains unchanged and stores only boundary results plus owned topology snapshots.']
limitations=['Three alternating-order Node trials are isolated classification measurements, not full browser/GPU/history timings.', 'Browser captures are individual fresh-load samples, optimized then nearby baseline then final optimized; other phases vary. No stable end-to-end gain or FPS guarantee is established.', 'Typed scratch arrays total 34,777,216 bytes for two million corners (500k quads); these are temporary, not a measured peak/total memory reduction. Cache snapshot memory is unchanged.', 'Parity comparison uses the retained ignored pre-change helper at wasm/tmp/viewer-boundary-table-before/meshBoundaryEdges.ts.', 'Existing bundle-size warning remains. Kernel/ABI, sketches, UI and runtime artifacts were not changed by this milestone. Other ongoing dirty viewer/core changes were preserved.', 'The existing reconstruction regression harness rewrote viewer-reconstruction-parity.json when rerun; a milestone-specific copy is saved as viewer-boundary-table-regression.json. Historical results remain in viewer-reconstruction-optimization.json/html.']
files=['../zspace_alice_webviewer/src/meshBoundaryEdges.ts','../zspace_alice_webviewer/tests/meshBoundaryTable.test.mjs','../zspace_alice_webviewer/reports/Alice-Viewer-Implementation-Roadmap.md','tests/performance/viewer-boundary-table-parity.mjs','reports/generate-boundary-table-report.py','reports/viewer-boundary-table-parity.json','reports/viewer-boundary-table-regression.json','reports/viewer-reconstruction-parity.json','reports/viewer-boundary-table-before.json','reports/viewer-boundary-table-after-first.json','reports/viewer-boundary-table-after-intermediate.json','reports/viewer-boundary-table-after.json','reports/viewer-boundary-table-optimization.json','reports/viewer-boundary-table-optimization.html','reports/viewer-boundary-table-500k.png']
data=dict(date='2026-10-08',changes=changes,nodeMedians=medians,node=node,browser=browser,verification=['Baseline and final npm run build passed; build after scratch-scope extraction passed.', '209 ordered boundary/membership fixtures, 18 full renderer comparisons passed.', 'Existing 62 surface/60 renderer parity cases and cache ownership/invalidation/LRU contracts passed.', 'Actual WebGPU viewer: 125k import, 500k Smooth, undo/redo and idle scheduling verified.'],limitations=limitations,changedFiles=files,nextPriority='Profile full publication ownership/copies and surface reconstruction before choosing the next bounded optimization; main-thread Smooth pauses remain.')
(root/'viewer-boundary-table-optimization.json').write_text(json.dumps(data,indent=2))
def lis(items): return '<ul>'+''.join('<li>'+html.escape(x)+'</li>' for x in items)+'</ul>'
rows=''.join(f"<tr><td>{r['faces']:,}</td><td>{r['beforeMs']:.1f}</td><td>{r['afterMs']:.1f}</td></tr>" for r in medians)
actions=''
for name,b in browser.items():
 cold=[p['durationMs'] for p in b['phases'] if p['name']=='boundary-incidence'][1]
 smooth=next(a['actionMs'] for a in b['actions'] if a['name'].startswith('smooth'))
 actions+=f'<tr><td>{name}</td><td>{cold:.1f}</td><td>{smooth:.1f}</td></tr>'
page='<!doctype html><meta charset="utf-8"><title>Cold boundary classification optimization</title><style>body{font:16px system-ui;max-width:1000px;margin:40px auto;padding:0 24px;line-height:1.6;background:#f7f9fb;color:#17212b}table{border-collapse:collapse;background:white}td,th{border:1px solid #ccd5df;padding:8px 16px;text-align:left}img{max-width:100%}code{overflow-wrap:anywhere}</style><h1>Cold boundary classification optimization</h1><p>08 October 2026 � viewer-only � public output order preserved</p><h2>Changes</h2>'+lis(changes)+'<h2>Node classification medians (ms)</h2><table><tr><th>Quads</th><th>Before</th><th>After</th></tr>'+rows+'</table><h2>Browser samples (ms)</h2><table><tr><th>Capture</th><th>Cold boundary</th><th>Full Smooth action</th></tr>'+actions+'</table><p>Cold boundary improved in the sampled runs. Full Smooth remains variable and blocks the main thread. Child/inclusive phase times must not be added together.</p><h2>Verification</h2>'+lis(data['verification'])+'<img src="viewer-boundary-table-500k.png" alt="Verified actual 500k viewer"><h2>Limitations</h2>'+lis(limitations)+'<h2>Next priority</h2><p>'+data['nextPriority']+'</p><h2>Changed files</h2>'+lis(files)+'<p>No commit or push.</p>'
(root/'viewer-boundary-table-optimization.html').write_text(page,encoding="utf-8")
print(json.dumps(dict(nodeMedians=medians,finalBrowser=browser['after']['actions'],samples=browser['after']['samples']),indent=2))
