import json, statistics, html
from pathlib import Path
viewer=Path('../zspace_alice_webviewer');root=Path('reports')
manifest=json.loads((viewer/'sketches/sketch_manifest.json').read_text())
operators=json.loads((viewer/'operators/operator_manifest.json').read_text())
timings=json.loads((root/'sketch-typed-buffer-timings.json').read_text())
rows=[]
for entry in manifest['sketches']:
 script=entry['script']
 path='JSON to separate toolsets WASM; owned typed mesh output' if script in ['sketch_importPanelisation.js','sketch_createCTube.js','sketch_createBranchCTube.js'] else 'JS authoring to owned typed mesh/graph output'
 note='Source assets are JSON files; computation is JS' if script in ['sketch_nanshaRoof.js','sketch_createPrimaryArch.js'] else 'Shared create/payload conversion now uses owned typed fast copies'
 if script=='sketch_nanshaRoof.js':note+='; planarity constraints use typed native upload when exported, with JSON stored in JS settings'
 if script=='sketch_createGraph.js':note+='; JS graph creation does not execute C++ zFnGraph'
 rows.append(dict(script=script,registered=True,path=path,viewer='All mesh outputs use shared optimized renderer; graph outputs use graph rendering',note=note))
rows.append(dict(script='sketch_bestFitForceDensity.js',registered=False,path='JSON input to separate vault/toolsets WASM; owned typed mesh output',viewer='Published mesh uses shared renderer',note='Present on disk but not listed in current sketch manifest; vault diagram/result metadata and branch result metadata still use JSON'))
medians=[]
for name in ['positions','connects']:
 t=[r for r in timings['timings'] if r['name']==name]
 medians.append(dict(name=name,beforeMs=statistics.median(r['beforeMs'] for r in t),afterMs=statistics.median(r['afterMs'] for r in t)))
files=['../zspace_alice_webviewer/src/numericBuffers.ts','../zspace_alice_webviewer/src/objects.ts','../zspace_alice_webviewer/src/kernels/zspaceJsKernel.ts','../zspace_alice_webviewer/tests/sketchTypedBuffers.test.mjs','../zspace_alice_webviewer/tests/sketchTypedBufferBenchmark.mjs','../zspace_alice_webviewer/reports/Alice-Viewer-Implementation-Roadmap.md','tests/performance/sketch-typed-buffer-benchmark.mjs','reports/generate-sketch-typed-audit.py','reports/sketch-typed-buffer-timings.json','reports/sketch-typed-audit.json','reports/sketch-typed-audit.html']
findings=['All nine registered sketches publish owned Float32/Uint32 geometry through zspace-js objects; ordinary arrays used during authoring are normalized before viewer publication. JSON source files are not evidence of JSON geometry upload to core.', 'Shared JS mesh/graph create and viewer payload conversions unnecessarily boxed typed input using Array.from and sometimes mapped it again. Fixed centrally in numericBuffers.ts, retaining owned copies and numeric conversion/uint clamp-floor behavior. Removed four materialized arrays used only for length checks.', 'Built-in Smooth, triangulate and mesh-analysis/replay load paths use loadPayloadIntoWasm -> uploadMeshBuffers. Installed core exposes typed buffer upload. Older runtime compatibility keeps the OBJ fallback; typed native failures are not silently retried as OBJ.', 'Nansha planarity uses uploadPlanarityBuffers when exports are available; constraints are still serialized/stored in JS parameters then parsed to typed buffers. The old-runtime fallback uses JSON FS input. This is not fully JSON-free.', 'C-Tubes, branch optimizer, panelisation and vault computation use a separate zspace_toolsets runtime with JSON inputs. Main mesh outputs are copied from typed WASM heap views. Diagnostics, diagrams, strip/branch result metadata can still use JSON.', 'Core mesh C++ optimizations are exercised when invoking current core WASM mesh operations. JS object creation does not run C++ mesh/graph methods. Separate toolsets runtime does not automatically inherit core binary changes; its linked mesh/topology implementation was not verified or rebuilt in this audit.', 'All published meshes use the shared optimized surface expansion, referenced-vertex bounds and cold boundary/cache paths for standard renderer callbacks. Solver dynamic update path remains available when its conditions hold. Graph display is a separate path.', 'Current live operator manifest has zero entries and operators/ contains only the manifest. Built-in operator execution/replay was audited; no unregistered custom operator can be claimed verified.']
verification=['Baseline and post-extraction npm run build passed (existing bundle-size warning).', '30 targeted tests passed, zero failed/skipped: numerical conversion and owned buffers, four existing generator sketches, actual installed core typed upload/smooth, transfer heap growth/free/fallback contracts, C-Tubes, real panelisation WASM, primary arch/deck, Nansha/planarity, origami, vault/statics and module loading.', 'Three alternating-order Node typed conversion trials on 500k-grid-sized inputs matched prior finite output bytes. These exclude triangulation/edge/normal computation, WASM, browser, history and GPU.', 'Installed core SHA256 unchanged: 27daad481b9c4a5d6b403b2cf15f79f4f2d7bcd066e3bbefb624d30c57799653. No native/runtime rebuild or sketch script edits.']
limits=['All nine manifest entries and the extra FDM script were inspected; targeted tests are not a full interactive run of every sketch/action. C-Tubes tests use a session test double; panelisation test executes real toolsets WASM.', 'Source asset JSON, metadata JSON, authoring arrays and internal JS triangulation/edge/color work remain. The audit did not convert every local array or redesign geometry derivation.', 'Snapshot-based parity tests require the retained pre-change files in wasm/tmp/sketch-typed-audit-before; installed runtime is needed for the real core test.', 'Separate toolsets typed input migration and verification/rebuild against current optimized core remain pending. No claim that all sketches are typed end to end or that every C++ optimization reaches toolsets.', 'Existing dirty user/sketch/operator/core/IO/graph work was preserved; no commit/push.']
data=dict(date='2026-10-08',registeredSketches=len(manifest['sketches']),liveOperators=len(operators.get('operators',[])),inventory=rows,findings=findings,verification=verification,limitations=limits,conversionMedians=medians,changedFiles=files,nextStep='Prioritize typed toolsets geometry input and verify/rebuild the toolsets-linked core in its own repository; retain separate structured metadata where appropriate.')
(root/'sketch-typed-audit.json').write_text(json.dumps(data,indent=2),encoding='utf-8')
def lis(items):return '<ul>'+''.join('<li>'+html.escape(x)+'</li>' for x in items)+'</ul>'
trs=''.join('<tr>'+''.join('<td>'+html.escape(str(r[k]))+'</td>' for k in ['script','registered','path','note'])+'</tr>' for r in rows)
bench=''.join(f"<tr><td>{r['name']}</td><td>{r['beforeMs']:.2f}</td><td>{r['afterMs']:.2f}</td></tr>" for r in medians)
page='<!doctype html><meta charset="utf-8"><title>Sketch/operator typed-buffer audit</title><style>body{font:16px system-ui;max-width:1150px;margin:40px auto;padding:0 20px;line-height:1.6;background:#f7f9fb;color:#18232e}table{border-collapse:collapse;background:white;width:100%}td,th{border:1px solid #ccd5df;padding:8px;text-align:left;overflow-wrap:anywhere}</style><h1>Sketch/operator typed-buffer audit</h1><p>08 October 2026 - 9 registered sketches, 1 extra script, 0 manifest operators</p><h2>Findings and fixes</h2>'+lis(findings)+'<h2>Sketch inventory</h2><table><tr><th>Script</th><th>Registered</th><th>Transfer path</th><th>Notes</th></tr>'+trs+'</table><h2>500k-sized typed conversion medians (ms)</h2><table><tr><th>Buffer</th><th>Before</th><th>After</th></tr>'+bench+'</table><p>Isolated Node conversion results, not end-to-end viewer timings.</p><h2>Verification</h2>'+lis(verification)+'<h2>Limits and pending work</h2>'+lis(limits)+'<h2>Next step</h2><p>'+data['nextStep']+'</p><h2>Changed files</h2>'+lis(files)
(root/'sketch-typed-audit.html').write_text(page,encoding='utf-8')
print(json.dumps(dict(sketches=data['registeredSketches'],operators=data['liveOperators'],medians=medians),indent=2))
