import json, statistics, html
from pathlib import Path
root=Path(__file__).parent
node=json.loads((root/'viewer-surface-bounds-parity.json').read_text())
browser={name:json.loads((root/f'viewer-surface-bounds-{name}.json').read_text()) for name in ['before','after']}
medians=[]
for faces in [125000,500000]:
 rows=[r for r in node['timings'] if r['faces']==faces]
 medians.append(dict(faces=faces,beforeBoundsMs=statistics.median(r['beforeBoundsMs'] for r in rows),afterBoundsMs=statistics.median(r['afterBoundsMs'] for r in rows)))
changes=['Add opt-in payload-normal, surface-buffer-expansion, surface-bounding-sphere and scene-payload-copy phases. Normal use performs no recording.', 'Compute face-color bounds from distinct referenced vertices with a temporary Uint8 marker. Keep THREE box-center and squared-distance arithmetic; exclude unused vertices. Vertex-color geometry still uses THREE unchanged.', 'Fall back to THREE for malformed indices/position lengths or nonfinite referenced coordinates, preserving its diagnostics.', 'Keep all defensive publication, active-payload and history copies. A measured publication copy was smaller than bounds, and ownership remains essential for mutable sketch inputs. No borrowed payload or shared buffer policy introduced.']
files=['../zspace_alice_webviewer/src/renderers.ts','../zspace_alice_webviewer/src/meshSurfaceBounds.ts','../zspace_alice_webviewer/tests/meshSurfaceBounds.test.mjs','../zspace_alice_webviewer/reports/Alice-Viewer-Implementation-Roadmap.md','tests/performance/viewer-surface-bounds-parity.mjs','reports/generate-surface-bounds-report.py','reports/viewer-surface-bounds-parity.json','reports/viewer-surface-bounds-before.json','reports/viewer-surface-bounds-after.json','reports/viewer-surface-bounds-optimization.json','reports/viewer-surface-bounds-optimization.html','reports/viewer-surface-bounds-500k.png']
limits=['Three alternating-order Node bounds trials exclude surface allocation/expansion, browser, GPU, history and publication. Full surface-buffer output is unchanged; its timings vary.', 'Browser samples are one fresh load before and after, without concurrent compilation/Node tests. No stable action median, FPS guarantee or broad responsiveness claim.', 'Marker storage at 500k/501501 vertices is 501501 bytes, local to the bounds call; no cache or total/peak memory reduction claimed.', 'The comparison harness uses the preserved ignored renderer snapshot at wasm/tmp/viewer-surface-bounds-before/renderers-profiled.ts.', 'Expected THREE diagnostics for nonfinite unused coordinates in vertex-color mode occurred in parity checks and are unchanged.', 'Existing bundle-size warning remains. Kernel/ABI, runtime artifacts, sketches and unrelated selection/display behavior were not modified. Other dirty user changes were preserved.']
data=dict(date='2026-10-08',changes=changes,nodeMedians=medians,node=node,browser=browser,verification=['Baseline, diagnostic and post-extraction npm run build passed.', '428 exact sphere comparisons, 62 surface-buffer and 60 renderer cases passed, including existing cache ownership/invalidation/LRU contracts.', 'Actual WebGPU viewer import 125k, Smooth to 500k, undo/redo and idle scheduling verified.'],limitations=limits,changedFiles=files,nextPriority='Measure stable per-phase action medians on representative meshes before choosing publication validation, transfer/native installation or worker ownership work. Smooth remains synchronous.')
(root/'viewer-surface-bounds-optimization.json').write_text(json.dumps(data,indent=2),encoding='utf-8')
def lis(items): return '<ul>'+''.join('<li>'+html.escape(x)+'</li>' for x in items)+'</ul>'
rows=''.join(f"<tr><td>{r['faces']:,}</td><td>{r['beforeBoundsMs']:.2f}</td><td>{r['afterBoundsMs']:.2f}</td></tr>" for r in medians)
phases=''
for name,b in browser.items():
 for phase in ['surface-buffer-expansion','surface-bounding-sphere','scene-payload-copy','scene-publication-inclusive','cpp-smooth-and-export']:
  values=[p['durationMs'] for p in b['phases'] if p['name']==phase]
  value=values[1 if phase in ['surface-buffer-expansion','surface-bounding-sphere','scene-payload-copy'] else 0]
  phases+=f'<tr><td>{name}</td><td>{phase}</td><td>{value:.2f}</td></tr>'
page='<!doctype html><meta charset="utf-8"><title>Surface bounds and publication profiling</title><style>body{font:16px system-ui;max-width:1000px;margin:40px auto;padding:0 24px;line-height:1.6;background:#f7f9fb;color:#17212b}table{border-collapse:collapse;background:white}td,th{border:1px solid #ccd5df;padding:8px 16px;text-align:left}img{max-width:100%}</style><h1>Surface bounds and publication profiling</h1><p>08 October 2026 - viewer only; exact sphere/output parity</p><h2>Changes</h2>'+lis(changes)+'<h2>Node bounds medians (ms)</h2><table><tr><th>Quads</th><th>Before</th><th>After</th></tr>'+rows+'</table><h2>Browser Smooth phase samples (ms)</h2><table><tr><th>Capture</th><th>Phase</th><th>Time</th></tr>'+phases+'</table><p>Inclusive phases contain their child phases. Do not sum them together.</p><h2>Verification</h2>'+lis(data['verification'])+'<pre>'+html.escape(json.dumps(browser['after']['actions'],indent=2))+'</pre><img src="viewer-surface-bounds-500k.png" alt="Verified actual 500k viewer"><h2>Limitations</h2>'+lis(limits)+'<h2>Next priority</h2><p>'+data['nextPriority']+'</p><h2>Changed files</h2>'+lis(files)+'<p>No commit or push.</p>'
(root/'viewer-surface-bounds-optimization.html').write_text(page,encoding='utf-8')
print(json.dumps(dict(medians=medians,actions={n:b['actions'] for n,b in browser.items()},samples=browser['after']['samples']),indent=2))
