# OpenUSD stays private to IO. Standard SDKs provide pxrConfig.cmake; split
# vendor devkits can supply headers/import libraries and runtime separately.
function(zspace_link_openusd target)
  if(NOT ZSPACE_OPENUSD_ROOT)
    message(FATAL_ERROR "ZSPACE_IO_WITH_OPENUSD=ON requires ZSPACE_OPENUSD_ROOT")
  endif()
  if(ZSPACE_OPENUSD_RUNTIME_ROOT)
    if(NOT WIN32)
      message(FATAL_ERROR "Split OpenUSD devkits are currently supported on Windows only")
    endif()
    target_include_directories(${target} SYSTEM PRIVATE "${ZSPACE_OPENUSD_ROOT}/include")
    set(ZSPACE_OPENUSD_EXTRA_INCLUDE_DIR "" CACHE PATH "Optional Python headers required by a vendor USD devkit")
    set(ZSPACE_OPENUSD_EXTRA_LIBRARY_DIR "" CACHE PATH "Optional Python libraries required by a vendor USD devkit")
    if(ZSPACE_OPENUSD_EXTRA_INCLUDE_DIR)
      target_include_directories(${target} SYSTEM PRIVATE "${ZSPACE_OPENUSD_EXTRA_INCLUDE_DIR}")
    endif()
    if(ZSPACE_OPENUSD_EXTRA_LIBRARY_DIR)
      target_link_directories(${target} PRIVATE "${ZSPACE_OPENUSD_EXTRA_LIBRARY_DIR}")
    endif()
    target_link_directories(${target} PRIVATE "${ZSPACE_OPENUSD_ROOT}/lib")
    foreach(component tf gf vt work plug ar sdf pcp usd usdGeom usdUtils)
      unset(zspaceUsdLibrary)
      find_library(zspaceUsdLibrary NAMES usd_${component} ${component}
        PATHS "${ZSPACE_OPENUSD_ROOT}/lib" NO_DEFAULT_PATH NO_CACHE REQUIRED)
      target_link_libraries(${target} PRIVATE "${zspaceUsdLibrary}")
    endforeach()
    # Python-enabled vendor devkits expose Python symbols through VtValue.
    # Headless SDKs do not need these optional libraries.
    foreach(component boost python)
      unset(zspaceUsdLibrary)
      find_library(zspaceUsdLibrary NAMES usd_${component}
        PATHS "${ZSPACE_OPENUSD_ROOT}/lib" NO_DEFAULT_PATH NO_CACHE)
      if(zspaceUsdLibrary)
        target_link_libraries(${target} PRIVATE "${zspaceUsdLibrary}")
      endif()
    endforeach()
  else()
    list(PREPEND CMAKE_PREFIX_PATH "${ZSPACE_OPENUSD_ROOT}")
    set(PXR_FIND_TBB_IN_CONFIG ON)
    find_package(pxr CONFIG REQUIRED PATHS "${ZSPACE_OPENUSD_ROOT}" NO_DEFAULT_PATH)
    target_link_libraries(${target} PRIVATE usd usdGeom usdUtils)
    if(EMSCRIPTEN)
      set(ZSPACE_OPENUSD_TARGETS "${PXR_LIBRARIES}" PARENT_SCOPE)
    endif()
  endif()
endfunction()
